### ISSUE TITLE
Working_directory

### ISSUE THREAD

**Issue by Ronalses** [enriikke/gatsby-gh-pages-action#34]
HI!

I have tried many things to run it in my app directory,
but nothing works.

Can't seem to find the working_directory

name: Gatsby Publish

on:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: apps/web
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}

**Comment by kenjdavidson** [comment]
At this point I don't think it's possible.  I was looking to see if this could convert a `/docs` folder to the `gh-pages` branch, but at this point it looks like the Gatsby project has to be at the root.

```shell
- project
  |- docs
  |- src
   \ README.md 
```

With the above folder structure (I think the same as yours) the goal would be to get `./docs/public` published to gh-pages instead of `./public` published.  Is that correct?  If so, I think this would be a solid addition.

**Comment by enriikke** [comment]
Addressed in https://github.com/enriikke/gatsby-gh-pages-action/pull/42 😃
