### ISSUE TITLE
Inconsistent tag name results in using old version

### ISSUE THREAD

**Issue by jasonnutter** [enriikke/gatsby-gh-pages-action#9]
The `README` advises using the following `uses` command:

```yml
- uses: enriikke/gatsby-gh-pages-action@v2
```

The problem is that the latest release is `2.1.1`, not `v2.1.1`, which means using `@v2` results in pulling down `v2.0.0`, instead of `2.1.1`.

**Comment by tmr08c** [comment]
@enriikke are you able to re-tag the non-`v` prefixed releases with a `v`? 

I tried using `@2`, to see if it would look for non `v`-prefixed versions, but it didn't work. 

As a workaround I am able to use the [branch syntax](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-using-versioned-actions), and specify `master`: 

```
- uses: enriikke/gatsby-gh-pages-action@master
```

**Comment by enriikke** [comment]
Thank you for the ping @tmr08c! and for the issue @jasonnutter! ✨ 

I have updated the tags. Would you mind checking and confirming it works on your end? 😃

**Comment by tmr08c** [comment]
Thanks for the quick update, @enriikke!

I [updated my action to use `@v2`](https://github.com/tmr08c/tmr08c.github.io/commit/db93e0d0148f05e77a9566f4f4e2ef178706f776), but it seems like it is still pulling an old version of the action because [it fails](https://github.com/tmr08c/tmr08c.github.io/runs/366903217) with the issue that was resolved in https://github.com/enriikke/gatsby-gh-pages-action/pull/6:

```
Building with: npm run gatsby build 
npm run gatsby build 
npm ERR! missing script: gatsby
```

I could try adding the minor version (`@v2.1`), but my understanding of the docs makes me think I shouldn't need to.

Looking at the releases page, it _seems_ like GH now recognizes `v2.1.1` should be used because it has the `Marketplace` tag: 

![Screen Shot 2019-12-29 at 11 28 04 AM](https://user-images.githubusercontent.com/691365/71559634-8e26ef80-2a2e-11ea-83b8-958865917e8f.png)


Interested if others run into the same issue, or if it's something on my end.

**Comment by jasonnutter** [comment]
I noticed the `version` field in `package.json` file hasn't been updated to `2.1.1`, probably worth fixing that also.

**Comment by enriikke** [comment]
Hi @tmr08c and @jasonnutter! Thank you for following up on this. There was a rouge `v2` tag that I had forgotten to update which was pointing to an old commit. This should be fixed now! I also updated the `package.json` version number on master. Let me know if it works on your end so we can close this issue.

Thank you both for all the helpful information and patience. 😃

**Comment by jasonnutter** [comment]
@enriikke Looks like it's fixed, thanks!
